version: '3.1'

services:

  web:
    image: webdevops/php-apache:8.0
    ports:
      - "8081:80"
    volumes:
      - ".:/app:cached"
      - "/Users/kentkent/.composer:/root/.composer:cached"
    restart: always
    command: ["supervisord", "&&", "composer", "config", "-g", "repo.packagist", "composer", "https://mirrors.aliyun.com/composer/"]
    environment:
      TZ: Asia/Shanghai
      PHP_DATE_TIMEZONE: Asia/Shanghai
      WEB_DOCUMENT_ROOT: /app/web
      WEB_ALIAS_DOMAIN: weeshop.test
      PHP_MEMORY_LIMIT: 1G
      XDEBUG_DISCOVER_CLIENT_HOST: "true"
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: "yes"
  db:
    image: mysql:8
    ports:
      - "3367:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql:delegated"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: drupal
